function sqlCredentials=getSqlCredentials()
    sqlCredentials = {
        'hostIP','172.20.138.142',...
        'user','dleventh',...
        'password','amygdala_probe',...
        'dbName','spikedb'
        };
end